### ISSUE TITLE
ESM packaging

### ISSUE THREAD

**Issue by curiousercreative** [julien-amblard/email-misspelled#37]
Please consider packaging as ES Module rather than CommonJS. https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by sl-julienamblard** [comment]
Hello @curiousercreative,
This is something I will working on.
Currently I'm on another package [(package-proxy)](https://github.com/sl-julienamblard/package-proxy), it will help the usage of ESM or commonjs depending on your working env. it will also resolve eventuals barrel files issue

**Comment by julien-amblard** [comment]
you can now uprade to v4.0.0
