### ISSUE TITLE
type keyword in lib/index.d.ts file causes build error

### ISSUE THREAD

**Issue by BotanMan** [julien-amblard/email-misspelled#48]
When I try to compile an angular library with typescript 3.4.5, I get the error
```
An unhandled exception occurred: node_modules/email-misspelled/lib/index.d.ts(3,1): error TS1128: Declaration or statement expected.
node_modules/email-misspelled/lib/index.d.ts(3,13): error TS1005: ';' expected.
node_modules/email-misspelled/lib/index.d.ts(3,109): error TS1005: ';' expected.
```

It happens due to  `type` keyword
https://github.com/sl-julienamblard/email-misspelled/blob/7e8e62fe67c39fc68deed5e9f726aa6755c97867/src/index.ts#L3

I'm not that good in TypeScript, but when I do remove the keyword it works fine. 

Does it really do something there? :)

**Comment by julien-amblard** [comment]
Hello, 
this was introduced since [typescript 4.5](https://www.typescriptlang.org/docs/handbook/modules.html#importing-types)
Actually typescript is in version 5.1, you may consider to upgrade your typescript version
