### ISSUE TITLE
Injection attempts are returned in URL encoding, which may help bypass sanitization

### ISSUE THREAD

**Issue by wbwarnerb** [julien-amblard/email-misspelled#78]
**Describe the bug**
The misspelled library will convert script tags to url encoded versions, which could help a threat actor refine XSS attempts.

**To Reproduce**
1. With a field running the library, enter an email such as asdf@gmil.com<script>alert(1)</script>
2. Tab out of the field, to trigger the library to suggest a correct spelling of gmail.

**Expected behavior**
I would expect to remove tags.  What it does is url encode the attempt, helping the attacker refine the code to a point that it might bypass sanitization of fields. 

**Screenshots**
<img width="476" alt="Screenshot 2024-10-15 at 2 48 49 PM" src="https://github.com/user-attachments/assets/50e14db0-4555-485c-9dba-44268b768034">

**Comment by julien-amblard** [comment]
Hello
I've tried but can't reproduce your behavior. Maybe the url encoding come from the implementation of your input OR from the plugin you seem's to according to the added picto in your screenshot.

Anyway, I've add a small sanitizer in the script based [on this regexp](https://github.com/julien-amblard/email-misspelled/blob/4.3.1/packages/email-misspelled/src/helpers/sanitize.ts)
